#!/bin/bash
echo `date`
echo `hostname`
curl -s -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose >> /dev/null
chmod a+x /usr/bin/docker-compose

openssl genrsa -out mydomain.key 2048
openssl req -new -key mydomain.key -passin pass:password -subj /C=US/ST=Kansas/L=Lawrence/O=OrgName/OU=OuName/CN=CnName/emailAddress=aos@mydomain.com -out mydomain.csr
openssl x509 -req -days 365 -in mydomain.csr -signkey mydomain.key -out mydomain.crt
cat mydomain.key mydomain.crt >> /etc/ssl/certs/mydomain.pem

yum -y install docker
service docker start

wget https://github.com/muthup/traceanalytics/raw/main/ant403.tar
tar -xvf ant403.tar
cd ant403
grep -RIl 'OSS_DOMAIN' | xargs sed -i -e "s/OSS_DOMAIN/opensearch-main.muthup.com/g" -e "s/OSSDOMAIN_USERNAME/admin/g" -e "s/OSSDOMAIN_PASSWORD/password/g"
/usr/bin/docker-compose up -d

yum -y install haproxy
