#!/bin/bash
echo `date`
echo `hostname`
curl -s -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose >> /dev/null
chmod a+x /usr/bin/docker-compose