apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mysql
  name: mysql-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS APM DEFAULT CHARACTER SET 'utf8';
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mysql
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.1.0
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          resources: {}
          volumeMounts:
            - name: mysql-configmap-config
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mysql-configmap-config
          configMap:
            name: mysql-config
status: {}
---

